//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://minvu/ice/sii", ConfigurationName="ICE_Propiedad_Habitacional.SII_orc_propiedades_habitacionales_prt_sii_prop_habita" +
        "cionalesComunaSoap")]
    public interface SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://rutpropiedadescomuna.Schema_rutpropiedadescomuna_rice) no coincide con el valor predeterminado (http://minvu/ice/sii).
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu/ice/sii/SII_orc_propiedades_habitacionales_prt_sii_prop_habitacional" +
            "esComuna/Propiedades_Habitacionales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ICE")]
        Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesResponse Propiedades_Habitacionales(Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu/ice/sii/SII_orc_propiedades_habitacionales_prt_sii_prop_habitacional" +
            "esComuna/Propiedades_Habitacionales", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesResponse> Propiedades_HabitacionalesAsync(Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SII.schemas.Schema_propiedades_habitacionales_conice")]
    public partial class Propiedades_habitacionales : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string dvField;
        
        private long periodoField;
        
        private string ussistField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("Dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Ussist {
            get {
                return this.ussistField;
            }
            set {
                this.ussistField = value;
                this.RaisePropertyChanged("Ussist");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rutpropiedadescomuna.Schema_rutpropiedadescomuna_rice")]
    public partial class ICE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERESULTADO rESULTADOField;
        
        private ArrayOfICEPROPIEDADPROPIEDAD[] rESPUESTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICERESULTADO RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PROPIEDAD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArrayOfICEPROPIEDADPROPIEDAD[] RESPUESTA {
            get {
                return this.rESPUESTAField;
            }
            set {
                this.rESPUESTAField = value;
                this.RaisePropertyChanged("RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rutpropiedadescomuna.Schema_rutpropiedadescomuna_rice")]
    public partial class ICERESULTADO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSTADOField;
        
        private string cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string iD_RESPUESTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ID_RESPUESTA {
            get {
                return this.iD_RESPUESTAField;
            }
            set {
                this.iD_RESPUESTAField = value;
                this.RaisePropertyChanged("ID_RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rutpropiedadescomuna.Schema_rutpropiedadescomuna_rice")]
    public partial class ArrayOfICEPROPIEDADPROPIEDAD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESTINOField;
        
        private string cOMUNAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESTINO {
            get {
                return this.dESTINOField;
            }
            set {
                this.dESTINOField = value;
                this.RaisePropertyChanged("DESTINO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string COMUNA {
            get {
                return this.cOMUNAField;
            }
            set {
                this.cOMUNAField = value;
                this.RaisePropertyChanged("COMUNA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Propiedades_Habitacionales", WrapperNamespace="http://minvu/ice/sii", IsWrapped=true)]
    public partial class Propiedades_HabitacionalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SII.schemas.Schema_propiedades_habitacionales_conice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://SII.schemas.Schema_propiedades_habitacionales_conice")]
        public Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_habitacionales Propiedades_habitacionales;
        
        public Propiedades_HabitacionalesRequest() {
        }
        
        public Propiedades_HabitacionalesRequest(Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_habitacionales Propiedades_habitacionales) {
            this.Propiedades_habitacionales = Propiedades_habitacionales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Propiedades_HabitacionalesResponse", WrapperNamespace="http://minvu/ice/sii", IsWrapped=true)]
    public partial class Propiedades_HabitacionalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rutpropiedadescomuna.Schema_rutpropiedadescomuna_rice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rutpropiedadescomuna.Schema_rutpropiedadescomuna_rice")]
        public Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.ICE ICE;
        
        public Propiedades_HabitacionalesResponse() {
        }
        
        public Propiedades_HabitacionalesResponse(Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.ICE ICE) {
            this.ICE = ICE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoapChannel : Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoap>, Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoap {
        
        public SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoapClient() {
        }
        
        public SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesResponse Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoap.Propiedades_Habitacionales(Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesRequest request) {
            return base.Channel.Propiedades_Habitacionales(request);
        }
        
        public Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.ICE Propiedades_Habitacionales(Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_habitacionales Propiedades_habitacionales1) {
            Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesRequest inValue = new Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesRequest();
            inValue.Propiedades_habitacionales = Propiedades_habitacionales1;
            Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesResponse retVal = ((Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoap)(this)).Propiedades_Habitacionales(inValue);
            return retVal.ICE;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesResponse> Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoap.Propiedades_HabitacionalesAsync(Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesRequest request) {
            return base.Channel.Propiedades_HabitacionalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesResponse> Propiedades_HabitacionalesAsync(Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_habitacionales Propiedades_habitacionales) {
            Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesRequest inValue = new Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.Propiedades_HabitacionalesRequest();
            inValue.Propiedades_habitacionales = Propiedades_habitacionales;
            return ((Minvu.SectoresMedios.IData.ICE_Propiedad_Habitacional.SII_orc_propiedades_habitacionales_prt_sii_prop_habitacionalesComunaSoap)(this)).Propiedades_HabitacionalesAsync(inValue);
        }
    }
}
