//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_Mideplan {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICE_Mideplan.fpsSoap")]
    public interface fpsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FichaProteccionSocial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Minvu.SectoresMedios.IData.ICE_Mideplan.ICE FichaProteccionSocial(Minvu.SectoresMedios.IData.ICE_Mideplan.Entrada input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FichaProteccionSocial", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Mideplan.ICE> FichaProteccionSocialAsync(Minvu.SectoresMedios.IData.ICE_Mideplan.Entrada input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMideplan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Minvu.SectoresMedios.IData.ICE_Mideplan.ICE TestMideplan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMideplan", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Mideplan.ICE> TestMideplanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Test2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Test2Async();
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Entrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string dvField;
        
        private long fecha_CorteField;
        
        private int ussistField;
        
        private int periodoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("Dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Fecha_Corte {
            get {
                return this.fecha_CorteField;
            }
            set {
                this.fecha_CorteField = value;
                this.RaisePropertyChanged("Fecha_Corte");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Ussist {
            get {
                return this.ussistField;
            }
            set {
                this.ussistField = value;
                this.RaisePropertyChanged("Ussist");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICERespuestaFichapuntajevivienda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ptjeField;
        
        private string indalleField;
        
        private string indhaciField;
        
        private string indtipvivField;
        
        private string inddaguaField;
        
        private string indeliexcField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ptje {
            get {
                return this.ptjeField;
            }
            set {
                this.ptjeField = value;
                this.RaisePropertyChanged("ptje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string indalle {
            get {
                return this.indalleField;
            }
            set {
                this.indalleField = value;
                this.RaisePropertyChanged("indalle");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string indhaci {
            get {
                return this.indhaciField;
            }
            set {
                this.indhaciField = value;
                this.RaisePropertyChanged("indhaci");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string indtipviv {
            get {
                return this.indtipvivField;
            }
            set {
                this.indtipvivField = value;
                this.RaisePropertyChanged("indtipviv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string inddagua {
            get {
                return this.inddaguaField;
            }
            set {
                this.inddaguaField = value;
                this.RaisePropertyChanged("inddagua");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string indeliexc {
            get {
                return this.indeliexcField;
            }
            set {
                this.indeliexcField = value;
                this.RaisePropertyChanged("indeliexc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICERespuestaFichaPersonasPersona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string runField;
        
        private string dvField;
        
        private string nombresField;
        
        private string ape1Field;
        
        private string ape2Field;
        
        private string sexoField;
        
        private string fec_nacField;
        
        private string parentescoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string run {
            get {
                return this.runField;
            }
            set {
                this.runField = value;
                this.RaisePropertyChanged("run");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ape1 {
            get {
                return this.ape1Field;
            }
            set {
                this.ape1Field = value;
                this.RaisePropertyChanged("ape1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ape2 {
            get {
                return this.ape2Field;
            }
            set {
                this.ape2Field = value;
                this.RaisePropertyChanged("ape2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string fec_nac {
            get {
                return this.fec_nacField;
            }
            set {
                this.fec_nacField = value;
                this.RaisePropertyChanged("fec_nac");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string parentesco {
            get {
                return this.parentescoField;
            }
            set {
                this.parentescoField = value;
                this.RaisePropertyChanged("parentesco");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICERespuestaFichaVivienda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string distrib_aguaField;
        
        private string sis_escretasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string distrib_agua {
            get {
                return this.distrib_aguaField;
            }
            set {
                this.distrib_aguaField = value;
                this.RaisePropertyChanged("distrib_agua");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sis_escretas {
            get {
                return this.sis_escretasField;
            }
            set {
                this.sis_escretasField = value;
                this.RaisePropertyChanged("sis_escretas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICERespuestaFicha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string folioField;
        
        private string ptjeField;
        
        private string fec_aplicField;
        
        private string fec_vencField;
        
        private string num_integField;
        
        private string comunaField;
        
        private string zonaField;
        
        private string uvField;
        
        private string nombre_agrup_habField;
        
        private string tipo_agrup_habField;
        
        private string codigo_agrup_habField;
        
        private string cod_manzanaField;
        
        private string cod_calleField;
        
        private string nom_calleField;
        
        private string num_domicilioField;
        
        private string block_casaField;
        
        private string depto_sitioField;
        
        private string cod_viviendaField;
        
        private string piezas_dormField;
        
        private string num_integ_no_parteField;
        
        private string etnia_originalField;
        
        private string ind_chsField;
        
        private string parentescoField;
        
        private string fec_cierreField;
        
        private string fec_puntajeField;
        
        private ICERespuestaFichaVivienda viviendaField;
        
        private ICERespuestaFichaPersonasPersona[] personasField;
        
        private ICERespuestaFichapuntajevivienda[] puntajeviviendaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ptje {
            get {
                return this.ptjeField;
            }
            set {
                this.ptjeField = value;
                this.RaisePropertyChanged("ptje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fec_aplic {
            get {
                return this.fec_aplicField;
            }
            set {
                this.fec_aplicField = value;
                this.RaisePropertyChanged("fec_aplic");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fec_venc {
            get {
                return this.fec_vencField;
            }
            set {
                this.fec_vencField = value;
                this.RaisePropertyChanged("fec_venc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string num_integ {
            get {
                return this.num_integField;
            }
            set {
                this.num_integField = value;
                this.RaisePropertyChanged("num_integ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("comuna");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("zona");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string uv {
            get {
                return this.uvField;
            }
            set {
                this.uvField = value;
                this.RaisePropertyChanged("uv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string nombre_agrup_hab {
            get {
                return this.nombre_agrup_habField;
            }
            set {
                this.nombre_agrup_habField = value;
                this.RaisePropertyChanged("nombre_agrup_hab");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string tipo_agrup_hab {
            get {
                return this.tipo_agrup_habField;
            }
            set {
                this.tipo_agrup_habField = value;
                this.RaisePropertyChanged("tipo_agrup_hab");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string codigo_agrup_hab {
            get {
                return this.codigo_agrup_habField;
            }
            set {
                this.codigo_agrup_habField = value;
                this.RaisePropertyChanged("codigo_agrup_hab");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string cod_manzana {
            get {
                return this.cod_manzanaField;
            }
            set {
                this.cod_manzanaField = value;
                this.RaisePropertyChanged("cod_manzana");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string cod_calle {
            get {
                return this.cod_calleField;
            }
            set {
                this.cod_calleField = value;
                this.RaisePropertyChanged("cod_calle");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string nom_calle {
            get {
                return this.nom_calleField;
            }
            set {
                this.nom_calleField = value;
                this.RaisePropertyChanged("nom_calle");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string num_domicilio {
            get {
                return this.num_domicilioField;
            }
            set {
                this.num_domicilioField = value;
                this.RaisePropertyChanged("num_domicilio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string block_casa {
            get {
                return this.block_casaField;
            }
            set {
                this.block_casaField = value;
                this.RaisePropertyChanged("block_casa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string depto_sitio {
            get {
                return this.depto_sitioField;
            }
            set {
                this.depto_sitioField = value;
                this.RaisePropertyChanged("depto_sitio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string cod_vivienda {
            get {
                return this.cod_viviendaField;
            }
            set {
                this.cod_viviendaField = value;
                this.RaisePropertyChanged("cod_vivienda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string piezas_dorm {
            get {
                return this.piezas_dormField;
            }
            set {
                this.piezas_dormField = value;
                this.RaisePropertyChanged("piezas_dorm");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string num_integ_no_parte {
            get {
                return this.num_integ_no_parteField;
            }
            set {
                this.num_integ_no_parteField = value;
                this.RaisePropertyChanged("num_integ_no_parte");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string etnia_original {
            get {
                return this.etnia_originalField;
            }
            set {
                this.etnia_originalField = value;
                this.RaisePropertyChanged("etnia_original");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ind_chs {
            get {
                return this.ind_chsField;
            }
            set {
                this.ind_chsField = value;
                this.RaisePropertyChanged("ind_chs");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string parentesco {
            get {
                return this.parentescoField;
            }
            set {
                this.parentescoField = value;
                this.RaisePropertyChanged("parentesco");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string fec_cierre {
            get {
                return this.fec_cierreField;
            }
            set {
                this.fec_cierreField = value;
                this.RaisePropertyChanged("fec_cierre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string fec_puntaje {
            get {
                return this.fec_puntajeField;
            }
            set {
                this.fec_puntajeField = value;
                this.RaisePropertyChanged("fec_puntaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public ICERespuestaFichaVivienda vivienda {
            get {
                return this.viviendaField;
            }
            set {
                this.viviendaField = value;
                this.RaisePropertyChanged("vivienda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        [System.Xml.Serialization.XmlArrayItemAttribute("persona", IsNullable=false)]
        public ICERespuestaFichaPersonasPersona[] personas {
            get {
                return this.personasField;
            }
            set {
                this.personasField = value;
                this.RaisePropertyChanged("personas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("puntajevivienda", Order=27)]
        public ICERespuestaFichapuntajevivienda[] puntajevivienda {
            get {
                return this.puntajeviviendaField;
            }
            set {
                this.puntajeviviendaField = value;
                this.RaisePropertyChanged("puntajevivienda");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICERespuestaStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descripField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descrip {
            get {
                return this.descripField;
            }
            set {
                this.descripField = value;
                this.RaisePropertyChanged("descrip");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICERespuestaEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string dvField;
        
        private string fec_cohorteField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fec_cohorte {
            get {
                return this.fec_cohorteField;
            }
            set {
                this.fec_cohorteField = value;
                this.RaisePropertyChanged("fec_cohorte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICERespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERespuestaEntrada[] entradaField;
        
        private ICERespuestaStatus[] statusField;
        
        private ICERespuestaFicha[] fichaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("entrada", Order=0)]
        public ICERespuestaEntrada[] entrada {
            get {
                return this.entradaField;
            }
            set {
                this.entradaField = value;
                this.RaisePropertyChanged("entrada");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("status", Order=1)]
        public ICERespuestaStatus[] status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ficha", Order=2)]
        public ICERespuestaFicha[] ficha {
            get {
                return this.fichaField;
            }
            set {
                this.fichaField = value;
                this.RaisePropertyChanged("ficha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICERESULTADO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSTADOField;
        
        private string cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string iD_RESPUESTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ID_RESPUESTA {
            get {
                return this.iD_RESPUESTAField;
            }
            set {
                this.iD_RESPUESTAField = value;
                this.RaisePropertyChanged("ID_RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ICE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oRIGENField;
        
        private ICERESULTADO[] rESULTADOField;
        
        private ICERespuesta[] respuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ORIGEN {
            get {
                return this.oRIGENField;
            }
            set {
                this.oRIGENField = value;
                this.RaisePropertyChanged("ORIGEN");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("RESULTADO", Order=1)]
        public ICERESULTADO[] RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("respuesta", Order=2)]
        public ICERespuesta[] respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface fpsSoapChannel : Minvu.SectoresMedios.IData.ICE_Mideplan.fpsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class fpsSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_Mideplan.fpsSoap>, Minvu.SectoresMedios.IData.ICE_Mideplan.fpsSoap {
        
        public fpsSoapClient() {
        }
        
        public fpsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public fpsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public fpsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public fpsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Minvu.SectoresMedios.IData.ICE_Mideplan.ICE FichaProteccionSocial(Minvu.SectoresMedios.IData.ICE_Mideplan.Entrada input) {
            return base.Channel.FichaProteccionSocial(input);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Mideplan.ICE> FichaProteccionSocialAsync(Minvu.SectoresMedios.IData.ICE_Mideplan.Entrada input) {
            return base.Channel.FichaProteccionSocialAsync(input);
        }
        
        public Minvu.SectoresMedios.IData.ICE_Mideplan.ICE TestMideplan() {
            return base.Channel.TestMideplan();
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Mideplan.ICE> TestMideplanAsync() {
            return base.Channel.TestMideplanAsync();
        }
        
        public string Test2() {
            return base.Channel.Test2();
        }
        
        public System.Threading.Tasks.Task<string> Test2Async() {
            return base.Channel.Test2Async();
        }
    }
}
