//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://minvu.cl/ICE/Bdd", ConfigurationName="ICE_Ahorro_SCOTIABANK_Bloqueo.BDD_orc_bloqueo_Prt_bdd_bloqueoSoap")]
    public interface BDD_orc_bloqueo_Prt_bdd_bloqueoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://infAhorro.Schema_bloqueo_conice) no coincide con el valor predeterminado (http://minvu.cl/ICE/Bdd).
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu.cl/ICE/Bdd/BDD_orc_bloqueo_Prt_bdd_bloqueo/Ope_prt_bdd_bloqueo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="part")]
        Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponse Ope_prt_bdd_bloqueo(Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu.cl/ICE/Bdd/BDD_orc_bloqueo_Prt_bdd_bloqueo/Ope_prt_bdd_bloqueo", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponse> Ope_prt_bdd_bloqueoAsync(Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://infAhorro.Schema_bloqueo_conice")]
    public partial class Bloqueo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string dvField;
        
        private string cuentaField;
        
        private string periodoField;
        
        private string ussistField;
        
        private string mesField;
        
        private string anoField;
        
        private string nllamadoField;
        
        private string programahabitacionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("Dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Ussist {
            get {
                return this.ussistField;
            }
            set {
                this.ussistField = value;
                this.RaisePropertyChanged("Ussist");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("Mes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
                this.RaisePropertyChanged("Ano");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Nllamado {
            get {
                return this.nllamadoField;
            }
            set {
                this.nllamadoField = value;
                this.RaisePropertyChanged("Nllamado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Programahabitacional {
            get {
                return this.programahabitacionalField;
            }
            set {
                this.programahabitacionalField = value;
                this.RaisePropertyChanged("Programahabitacional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://minvu.cl/ICE/Bdd")]
    public partial class Ope_prt_bdd_bloqueoResponsePart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Ope_prt_bdd_bloqueoResponsePartRESULTADO rESULTADOField;
        
        private Ope_prt_bdd_bloqueoResponsePartResp_Minvu resp_MinvuField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Ope_prt_bdd_bloqueoResponsePartRESULTADO RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Ope_prt_bdd_bloqueoResponsePartResp_Minvu Resp_Minvu {
            get {
                return this.resp_MinvuField;
            }
            set {
                this.resp_MinvuField = value;
                this.RaisePropertyChanged("Resp_Minvu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://minvu.cl/ICE/Bdd")]
    public partial class Ope_prt_bdd_bloqueoResponsePartRESULTADO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eSTADOField;
        
        private long cODIGOField;
        
        private string dESCRIPCIONField;
        
        private long iD_RESPUESTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long ID_RESPUESTA {
            get {
                return this.iD_RESPUESTAField;
            }
            set {
                this.iD_RESPUESTAField = value;
                this.RaisePropertyChanged("ID_RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://minvu.cl/ICE/Bdd")]
    public partial class Ope_prt_bdd_bloqueoResponsePartResp_Minvu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Ope_prt_bdd_bloqueoResponsePartResp_MinvuCabecera cabeceraField;
        
        private Ope_prt_bdd_bloqueoResponsePartResp_MinvuEntrada entradaField;
        
        private Ope_prt_bdd_bloqueoResponsePartResp_MinvuSalida salidaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Ope_prt_bdd_bloqueoResponsePartResp_MinvuCabecera Cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("Cabecera");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Ope_prt_bdd_bloqueoResponsePartResp_MinvuEntrada Entrada {
            get {
                return this.entradaField;
            }
            set {
                this.entradaField = value;
                this.RaisePropertyChanged("Entrada");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Ope_prt_bdd_bloqueoResponsePartResp_MinvuSalida Salida {
            get {
                return this.salidaField;
            }
            set {
                this.salidaField = value;
                this.RaisePropertyChanged("Salida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://minvu.cl/ICE/Bdd")]
    public partial class Ope_prt_bdd_bloqueoResponsePartResp_MinvuCabecera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long id_msgField;
        
        private string id_servicioField;
        
        private string ipField;
        
        private string uRLField;
        
        private string fechaField;
        
        private string horaField;
        
        private string resultadoField;
        
        private string glosa_errField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long Id_msg {
            get {
                return this.id_msgField;
            }
            set {
                this.id_msgField = value;
                this.RaisePropertyChanged("Id_msg");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Id_servicio {
            get {
                return this.id_servicioField;
            }
            set {
                this.id_servicioField = value;
                this.RaisePropertyChanged("Id_servicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("IP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("Hora");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Glosa_err {
            get {
                return this.glosa_errField;
            }
            set {
                this.glosa_errField = value;
                this.RaisePropertyChanged("Glosa_err");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://minvu.cl/ICE/Bdd")]
    public partial class Ope_prt_bdd_bloqueoResponsePartResp_MinvuEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string num_ctaField;
        
        private long rutField;
        
        private string dv_rutField;
        
        private string mesField;
        
        private string usuarioField;
        
        private long sol_correlField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Num_cta {
            get {
                return this.num_ctaField;
            }
            set {
                this.num_ctaField = value;
                this.RaisePropertyChanged("Num_cta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Dv_rut {
            get {
                return this.dv_rutField;
            }
            set {
                this.dv_rutField = value;
                this.RaisePropertyChanged("Dv_rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("Mes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long Sol_correl {
            get {
                return this.sol_correlField;
            }
            set {
                this.sol_correlField = value;
                this.RaisePropertyChanged("Sol_correl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://minvu.cl/ICE/Bdd")]
    public partial class Ope_prt_bdd_bloqueoResponsePartResp_MinvuSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string status_ctaField;
        
        private string fecha_aperturaField;
        
        private int reajusteField;
        
        private string giros_posterioresField;
        
        private int plazo_orig_mesesField;
        
        private long monto_orig_UFField;
        
        private long plazo_modificadoField;
        
        private long monto_modificado_UFField;
        
        private long saldo_UF_mesField;
        
        private long saldo_UF_diaField;
        
        private string fecha_inicioField;
        
        private Ope_prt_bdd_bloqueoResponsePartResp_MinvuSalidaSA[] saField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Status_cta {
            get {
                return this.status_ctaField;
            }
            set {
                this.status_ctaField = value;
                this.RaisePropertyChanged("Status_cta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Fecha_apertura {
            get {
                return this.fecha_aperturaField;
            }
            set {
                this.fecha_aperturaField = value;
                this.RaisePropertyChanged("Fecha_apertura");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Reajuste {
            get {
                return this.reajusteField;
            }
            set {
                this.reajusteField = value;
                this.RaisePropertyChanged("Reajuste");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Giros_posteriores {
            get {
                return this.giros_posterioresField;
            }
            set {
                this.giros_posterioresField = value;
                this.RaisePropertyChanged("Giros_posteriores");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int Plazo_orig_meses {
            get {
                return this.plazo_orig_mesesField;
            }
            set {
                this.plazo_orig_mesesField = value;
                this.RaisePropertyChanged("Plazo_orig_meses");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long Monto_orig_UF {
            get {
                return this.monto_orig_UFField;
            }
            set {
                this.monto_orig_UFField = value;
                this.RaisePropertyChanged("Monto_orig_UF");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long Plazo_modificado {
            get {
                return this.plazo_modificadoField;
            }
            set {
                this.plazo_modificadoField = value;
                this.RaisePropertyChanged("Plazo_modificado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long Monto_modificado_UF {
            get {
                return this.monto_modificado_UFField;
            }
            set {
                this.monto_modificado_UFField = value;
                this.RaisePropertyChanged("Monto_modificado_UF");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long Saldo_UF_mes {
            get {
                return this.saldo_UF_mesField;
            }
            set {
                this.saldo_UF_mesField = value;
                this.RaisePropertyChanged("Saldo_UF_mes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long Saldo_UF_dia {
            get {
                return this.saldo_UF_diaField;
            }
            set {
                this.saldo_UF_diaField = value;
                this.RaisePropertyChanged("Saldo_UF_dia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                this.fecha_inicioField = value;
                this.RaisePropertyChanged("Fecha_inicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Sa", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public Ope_prt_bdd_bloqueoResponsePartResp_MinvuSalidaSA[] Sa {
            get {
                return this.saField;
            }
            set {
                this.saField = value;
                this.RaisePropertyChanged("Sa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://minvu.cl/ICE/Bdd")]
    public partial class Ope_prt_bdd_bloqueoResponsePartResp_MinvuSalidaSA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sField;
        
        private bool sFieldSpecified;
        
        private long valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int S {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
                this.RaisePropertyChanged("S");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSpecified {
            get {
                return this.sFieldSpecified;
            }
            set {
                this.sFieldSpecified = value;
                this.RaisePropertyChanged("SSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ope_prt_bdd_bloqueo", WrapperNamespace="http://minvu.cl/ICE/Bdd", IsWrapped=true)]
    public partial class Ope_prt_bdd_bloqueoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://infAhorro.Schema_bloqueo_conice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://infAhorro.Schema_bloqueo_conice")]
        public Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Bloqueo Bloqueo;
        
        public Ope_prt_bdd_bloqueoRequest() {
        }
        
        public Ope_prt_bdd_bloqueoRequest(Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Bloqueo Bloqueo) {
            this.Bloqueo = Bloqueo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ope_prt_bdd_bloqueoResponse", WrapperNamespace="http://minvu.cl/ICE/Bdd", IsWrapped=true)]
    public partial class Ope_prt_bdd_bloqueoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://minvu.cl/ICE/Bdd", Order=0)]
        public Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponsePart part;
        
        public Ope_prt_bdd_bloqueoResponse() {
        }
        
        public Ope_prt_bdd_bloqueoResponse(Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponsePart part) {
            this.part = part;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BDD_orc_bloqueo_Prt_bdd_bloqueoSoapChannel : Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.BDD_orc_bloqueo_Prt_bdd_bloqueoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDD_orc_bloqueo_Prt_bdd_bloqueoSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.BDD_orc_bloqueo_Prt_bdd_bloqueoSoap>, Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.BDD_orc_bloqueo_Prt_bdd_bloqueoSoap {
        
        public BDD_orc_bloqueo_Prt_bdd_bloqueoSoapClient() {
        }
        
        public BDD_orc_bloqueo_Prt_bdd_bloqueoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDD_orc_bloqueo_Prt_bdd_bloqueoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDD_orc_bloqueo_Prt_bdd_bloqueoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDD_orc_bloqueo_Prt_bdd_bloqueoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponse Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.BDD_orc_bloqueo_Prt_bdd_bloqueoSoap.Ope_prt_bdd_bloqueo(Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoRequest request) {
            return base.Channel.Ope_prt_bdd_bloqueo(request);
        }
        
        public Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponsePart Ope_prt_bdd_bloqueo(Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Bloqueo Bloqueo) {
            Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoRequest inValue = new Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoRequest();
            inValue.Bloqueo = Bloqueo;
            Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponse retVal = ((Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.BDD_orc_bloqueo_Prt_bdd_bloqueoSoap)(this)).Ope_prt_bdd_bloqueo(inValue);
            return retVal.part;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponse> Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.BDD_orc_bloqueo_Prt_bdd_bloqueoSoap.Ope_prt_bdd_bloqueoAsync(Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoRequest request) {
            return base.Channel.Ope_prt_bdd_bloqueoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoResponse> Ope_prt_bdd_bloqueoAsync(Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Bloqueo Bloqueo) {
            Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoRequest inValue = new Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.Ope_prt_bdd_bloqueoRequest();
            inValue.Bloqueo = Bloqueo;
            return ((Minvu.SectoresMedios.IData.ICE_Ahorro_SCOTIABANK_Bloqueo.BDD_orc_bloqueo_Prt_bdd_bloqueoSoap)(this)).Ope_prt_bdd_bloqueoAsync(inValue);
        }
    }
}
