//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.RegistroTecnico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contratista", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contratista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Rut {
            get {
                return this.RutField;
            }
            set {
                if ((this.RutField.Equals(value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistroTecnico.RegContratistasSoap")]
    public interface RegContratistasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Input del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoContratista", ReplyAction="*")]
        Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaResponse EstadoContratista(Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoContratista", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaResponse> EstadoContratistaAsync(Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstadoContratistaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstadoContratista", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequestBody Body;
        
        public EstadoContratistaRequest() {
        }
        
        public EstadoContratistaRequest(Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoContratistaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Minvu.SectoresMedios.IData.RegistroTecnico.Contratista Input;
        
        public EstadoContratistaRequestBody() {
        }
        
        public EstadoContratistaRequestBody(Minvu.SectoresMedios.IData.RegistroTecnico.Contratista Input) {
            this.Input = Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstadoContratistaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstadoContratistaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaResponseBody Body;
        
        public EstadoContratistaResponse() {
        }
        
        public EstadoContratistaResponse(Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoContratistaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EstadoContratistaResult;
        
        public EstadoContratistaResponseBody() {
        }
        
        public EstadoContratistaResponseBody(string EstadoContratistaResult) {
            this.EstadoContratistaResult = EstadoContratistaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegContratistasSoapChannel : Minvu.SectoresMedios.IData.RegistroTecnico.RegContratistasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegContratistasSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.RegistroTecnico.RegContratistasSoap>, Minvu.SectoresMedios.IData.RegistroTecnico.RegContratistasSoap {
        
        public RegContratistasSoapClient() {
        }
        
        public RegContratistasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegContratistasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegContratistasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegContratistasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaResponse Minvu.SectoresMedios.IData.RegistroTecnico.RegContratistasSoap.EstadoContratista(Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequest request) {
            return base.Channel.EstadoContratista(request);
        }
        
        public string EstadoContratista(Minvu.SectoresMedios.IData.RegistroTecnico.Contratista Input) {
            Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequest inValue = new Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequest();
            inValue.Body = new Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequestBody();
            inValue.Body.Input = Input;
            Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaResponse retVal = ((Minvu.SectoresMedios.IData.RegistroTecnico.RegContratistasSoap)(this)).EstadoContratista(inValue);
            return retVal.Body.EstadoContratistaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaResponse> Minvu.SectoresMedios.IData.RegistroTecnico.RegContratistasSoap.EstadoContratistaAsync(Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequest request) {
            return base.Channel.EstadoContratistaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaResponse> EstadoContratistaAsync(Minvu.SectoresMedios.IData.RegistroTecnico.Contratista Input) {
            Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequest inValue = new Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequest();
            inValue.Body = new Minvu.SectoresMedios.IData.RegistroTecnico.EstadoContratistaRequestBody();
            inValue.Body.Input = Input;
            return ((Minvu.SectoresMedios.IData.RegistroTecnico.RegContratistasSoap)(this)).EstadoContratistaAsync(inValue);
        }
    }
}
