//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_Contratista {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entrada", Namespace="http://minvu.WSICE.Contratistas/")]
    [System.SerializableAttribute()]
    public partial class Entrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Rut {
            get {
                return this.RutField;
            }
            set {
                if ((this.RutField.Equals(value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://minvu.WSICE.Contratistas/", ConfigurationName="ICE_Contratista.ContratistaSoap")]
    public interface ContratistaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento input del espacio de nombres http://minvu.WSICE.Contratistas/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu.WSICE.Contratistas/ObtenerContratistaPorRut", ReplyAction="*")]
        Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutResponse ObtenerContratistaPorRut(Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu.WSICE.Contratistas/ObtenerContratistaPorRut", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutResponse> ObtenerContratistaPorRutAsync(Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerContratistaPorRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerContratistaPorRut", Namespace="http://minvu.WSICE.Contratistas/", Order=0)]
        public Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequestBody Body;
        
        public ObtenerContratistaPorRutRequest() {
        }
        
        public ObtenerContratistaPorRutRequest(Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://minvu.WSICE.Contratistas/")]
    public partial class ObtenerContratistaPorRutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Minvu.SectoresMedios.IData.ICE_Contratista.Entrada input;
        
        public ObtenerContratistaPorRutRequestBody() {
        }
        
        public ObtenerContratistaPorRutRequestBody(Minvu.SectoresMedios.IData.ICE_Contratista.Entrada input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerContratistaPorRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerContratistaPorRutResponse", Namespace="http://minvu.WSICE.Contratistas/", Order=0)]
        public Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutResponseBody Body;
        
        public ObtenerContratistaPorRutResponse() {
        }
        
        public ObtenerContratistaPorRutResponse(Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://minvu.WSICE.Contratistas/")]
    public partial class ObtenerContratistaPorRutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerContratistaPorRutResult;
        
        public ObtenerContratistaPorRutResponseBody() {
        }
        
        public ObtenerContratistaPorRutResponseBody(string ObtenerContratistaPorRutResult) {
            this.ObtenerContratistaPorRutResult = ObtenerContratistaPorRutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContratistaSoapChannel : Minvu.SectoresMedios.IData.ICE_Contratista.ContratistaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContratistaSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_Contratista.ContratistaSoap>, Minvu.SectoresMedios.IData.ICE_Contratista.ContratistaSoap {
        
        public ContratistaSoapClient() {
        }
        
        public ContratistaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContratistaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratistaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratistaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutResponse Minvu.SectoresMedios.IData.ICE_Contratista.ContratistaSoap.ObtenerContratistaPorRut(Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequest request) {
            return base.Channel.ObtenerContratistaPorRut(request);
        }
        
        public string ObtenerContratistaPorRut(Minvu.SectoresMedios.IData.ICE_Contratista.Entrada input) {
            Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequest inValue = new Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequest();
            inValue.Body = new Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequestBody();
            inValue.Body.input = input;
            Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutResponse retVal = ((Minvu.SectoresMedios.IData.ICE_Contratista.ContratistaSoap)(this)).ObtenerContratistaPorRut(inValue);
            return retVal.Body.ObtenerContratistaPorRutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutResponse> Minvu.SectoresMedios.IData.ICE_Contratista.ContratistaSoap.ObtenerContratistaPorRutAsync(Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequest request) {
            return base.Channel.ObtenerContratistaPorRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutResponse> ObtenerContratistaPorRutAsync(Minvu.SectoresMedios.IData.ICE_Contratista.Entrada input) {
            Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequest inValue = new Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequest();
            inValue.Body = new Minvu.SectoresMedios.IData.ICE_Contratista.ObtenerContratistaPorRutRequestBody();
            inValue.Body.input = input;
            return ((Minvu.SectoresMedios.IData.ICE_Contratista.ContratistaSoap)(this)).ObtenerContratistaPorRutAsync(inValue);
        }
    }
}
