//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_RegistroCivil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://minvu/ice/regcivil", ConfigurationName="ICE_RegistroCivil.REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap")]
    public interface REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://info_persona.Schema_info_persona_Rice) no coincide con el valor predeterminado (http://minvu/ice/regcivil).
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu/ice/regcivil/REGCIVIL_orc_datos_persona_prt_regcivil_info_persona/op" +
            "e_prt_regcivil_info_persona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ICE")]
        Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaResponse ope_prt_regcivil_info_persona(Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu/ice/regcivil/REGCIVIL_orc_datos_persona_prt_regcivil_info_persona/op" +
            "e_prt_regcivil_info_persona", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaResponse> ope_prt_regcivil_info_personaAsync(Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_conice")]
    public partial class Infopersona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long rutField;
        
        private string dvField;
        
        private double periodoField;
        
        private int ussistField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("Dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int Ussist {
            get {
                return this.ussistField;
            }
            set {
                this.ussistField = value;
                this.RaisePropertyChanged("Ussist");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERESULTADO rESULTADOField;
        
        private ICEMinvuRutData minvuRutDataField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICERESULTADO RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ICEMinvuRutData minvuRutData {
            get {
                return this.minvuRutDataField;
            }
            set {
                this.minvuRutDataField = value;
                this.RaisePropertyChanged("minvuRutData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICERESULTADO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eSTADOField;
        
        private string cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string iD_RESPUESTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ID_RESPUESTA {
            get {
                return this.iD_RESPUESTAField;
            }
            set {
                this.iD_RESPUESTAField = value;
                this.RaisePropertyChanged("ID_RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICEMinvuRutDataPersona personaField;
        
        private ICEMinvuRutDataMatrimonio[] matrimonioField;
        
        private ICEMinvuRutDataHijo[] hijoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICEMinvuRutDataPersona persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("matrimonio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ICEMinvuRutDataMatrimonio[] matrimonio {
            get {
                return this.matrimonioField;
            }
            set {
                this.matrimonioField = value;
                this.RaisePropertyChanged("matrimonio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("hijo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ICEMinvuRutDataHijo[] hijo {
            get {
                return this.hijoField;
            }
            set {
                this.hijoField = value;
                this.RaisePropertyChanged("hijo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataPersona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nombresField;
        
        private string apPaternoField;
        
        private string apMaternoField;
        
        private string fechaNaciField;
        
        private string fechaDefunField;
        
        private string estadoCivilField;
        
        private string sexoField;
        
        private ICEMinvuRutDataPersonaDiscapacidad discapacidadField;
        
        private ICEMinvuRutDataPersonaDiscapacidadRN discapacidadRNField;
        
        private string nacionalidadField;
        
        private string paisOrigenField;
        
        private string[] textField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apPaterno {
            get {
                return this.apPaternoField;
            }
            set {
                this.apPaternoField = value;
                this.RaisePropertyChanged("apPaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string apMaterno {
            get {
                return this.apMaternoField;
            }
            set {
                this.apMaternoField = value;
                this.RaisePropertyChanged("apMaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaNaci {
            get {
                return this.fechaNaciField;
            }
            set {
                this.fechaNaciField = value;
                this.RaisePropertyChanged("fechaNaci");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaDefun {
            get {
                return this.fechaDefunField;
            }
            set {
                this.fechaDefunField = value;
                this.RaisePropertyChanged("fechaDefun");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("estadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ICEMinvuRutDataPersonaDiscapacidad discapacidad {
            get {
                return this.discapacidadField;
            }
            set {
                this.discapacidadField = value;
                this.RaisePropertyChanged("discapacidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public ICEMinvuRutDataPersonaDiscapacidadRN discapacidadRN {
            get {
                return this.discapacidadRNField;
            }
            set {
                this.discapacidadRNField = value;
                this.RaisePropertyChanged("discapacidadRN");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string paisOrigen {
            get {
                return this.paisOrigenField;
            }
            set {
                this.paisOrigenField = value;
                this.RaisePropertyChanged("paisOrigen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataPersonaDiscapacidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaVencField;
        
        private string mentalField;
        
        private string sensorialField;
        
        private string fisicaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaVenc {
            get {
                return this.fechaVencField;
            }
            set {
                this.fechaVencField = value;
                this.RaisePropertyChanged("fechaVenc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mental {
            get {
                return this.mentalField;
            }
            set {
                this.mentalField = value;
                this.RaisePropertyChanged("mental");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sensorial {
            get {
                return this.sensorialField;
            }
            set {
                this.sensorialField = value;
                this.RaisePropertyChanged("sensorial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fisica {
            get {
                return this.fisicaField;
            }
            set {
                this.fisicaField = value;
                this.RaisePropertyChanged("fisica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataPersonaDiscapacidadRN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string indPermanenteField;
        
        private string fechaProximoDictamenField;
        
        private string gradoDiscapacidadGlobalField;
        
        private string causaPrincipalField;
        
        private ICEMinvuRutDataPersonaDiscapacidadRNListaCausaSecundaria[] listaCausaSecundariaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string indPermanente {
            get {
                return this.indPermanenteField;
            }
            set {
                this.indPermanenteField = value;
                this.RaisePropertyChanged("indPermanente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string fechaProximoDictamen {
            get {
                return this.fechaProximoDictamenField;
            }
            set {
                this.fechaProximoDictamenField = value;
                this.RaisePropertyChanged("fechaProximoDictamen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string gradoDiscapacidadGlobal {
            get {
                return this.gradoDiscapacidadGlobalField;
            }
            set {
                this.gradoDiscapacidadGlobalField = value;
                this.RaisePropertyChanged("gradoDiscapacidadGlobal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string causaPrincipal {
            get {
                return this.causaPrincipalField;
            }
            set {
                this.causaPrincipalField = value;
                this.RaisePropertyChanged("causaPrincipal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaCausaSecundaria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public ICEMinvuRutDataPersonaDiscapacidadRNListaCausaSecundaria[] listaCausaSecundaria {
            get {
                return this.listaCausaSecundariaField;
            }
            set {
                this.listaCausaSecundariaField = value;
                this.RaisePropertyChanged("listaCausaSecundaria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataPersonaDiscapacidadRNListaCausaSecundaria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string causaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string causa {
            get {
                return this.causaField;
            }
            set {
                this.causaField = value;
                this.RaisePropertyChanged("causa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataMatrimonio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICEMinvuRutDataMatrimonioConyuge[] conyugeField;
        
        private string capitulacionField;
        
        private string fechaInscripcionMatrimonioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("conyuge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICEMinvuRutDataMatrimonioConyuge[] conyuge {
            get {
                return this.conyugeField;
            }
            set {
                this.conyugeField = value;
                this.RaisePropertyChanged("conyuge");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string capitulacion {
            get {
                return this.capitulacionField;
            }
            set {
                this.capitulacionField = value;
                this.RaisePropertyChanged("capitulacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaInscripcionMatrimonio {
            get {
                return this.fechaInscripcionMatrimonioField;
            }
            set {
                this.fechaInscripcionMatrimonioField = value;
                this.RaisePropertyChanged("fechaInscripcionMatrimonio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataMatrimonioConyuge : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorField;
        
        private string rutField;
        
        private string nombresField;
        
        private string apPaternoField;
        
        private string apMaternoField;
        
        private string fechaNaciField;
        
        private string fechaDefunField;
        
        private string estadoCivilField;
        
        private string sexoField;
        
        private ICEMinvuRutDataMatrimonioConyugeDiscapacidad discapacidadField;
        
        private ICEMinvuRutDataMatrimonioConyugeDiscapacidadRN discapacidadRNField;
        
        private string[] textField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string apPaterno {
            get {
                return this.apPaternoField;
            }
            set {
                this.apPaternoField = value;
                this.RaisePropertyChanged("apPaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string apMaterno {
            get {
                return this.apMaternoField;
            }
            set {
                this.apMaternoField = value;
                this.RaisePropertyChanged("apMaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaNaci {
            get {
                return this.fechaNaciField;
            }
            set {
                this.fechaNaciField = value;
                this.RaisePropertyChanged("fechaNaci");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fechaDefun {
            get {
                return this.fechaDefunField;
            }
            set {
                this.fechaDefunField = value;
                this.RaisePropertyChanged("fechaDefun");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("estadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ICEMinvuRutDataMatrimonioConyugeDiscapacidad discapacidad {
            get {
                return this.discapacidadField;
            }
            set {
                this.discapacidadField = value;
                this.RaisePropertyChanged("discapacidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public ICEMinvuRutDataMatrimonioConyugeDiscapacidadRN discapacidadRN {
            get {
                return this.discapacidadRNField;
            }
            set {
                this.discapacidadRNField = value;
                this.RaisePropertyChanged("discapacidadRN");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataMatrimonioConyugeDiscapacidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaVencField;
        
        private string mentalField;
        
        private string sensorialField;
        
        private string fisicaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaVenc {
            get {
                return this.fechaVencField;
            }
            set {
                this.fechaVencField = value;
                this.RaisePropertyChanged("fechaVenc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mental {
            get {
                return this.mentalField;
            }
            set {
                this.mentalField = value;
                this.RaisePropertyChanged("mental");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sensorial {
            get {
                return this.sensorialField;
            }
            set {
                this.sensorialField = value;
                this.RaisePropertyChanged("sensorial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fisica {
            get {
                return this.fisicaField;
            }
            set {
                this.fisicaField = value;
                this.RaisePropertyChanged("fisica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataMatrimonioConyugeDiscapacidadRN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string indPermanenteField;
        
        private string fechaProximoDictamenField;
        
        private string gradoDiscapacidadGlobalField;
        
        private string causaPrincipalField;
        
        private ICEMinvuRutDataMatrimonioConyugeDiscapacidadRNListaCausaSecundaria[] listaCausaSecundariaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string indPermanente {
            get {
                return this.indPermanenteField;
            }
            set {
                this.indPermanenteField = value;
                this.RaisePropertyChanged("indPermanente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string fechaProximoDictamen {
            get {
                return this.fechaProximoDictamenField;
            }
            set {
                this.fechaProximoDictamenField = value;
                this.RaisePropertyChanged("fechaProximoDictamen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string gradoDiscapacidadGlobal {
            get {
                return this.gradoDiscapacidadGlobalField;
            }
            set {
                this.gradoDiscapacidadGlobalField = value;
                this.RaisePropertyChanged("gradoDiscapacidadGlobal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string causaPrincipal {
            get {
                return this.causaPrincipalField;
            }
            set {
                this.causaPrincipalField = value;
                this.RaisePropertyChanged("causaPrincipal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaCausaSecundaria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public ICEMinvuRutDataMatrimonioConyugeDiscapacidadRNListaCausaSecundaria[] listaCausaSecundaria {
            get {
                return this.listaCausaSecundariaField;
            }
            set {
                this.listaCausaSecundariaField = value;
                this.RaisePropertyChanged("listaCausaSecundaria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataMatrimonioConyugeDiscapacidadRNListaCausaSecundaria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string causaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string causa {
            get {
                return this.causaField;
            }
            set {
                this.causaField = value;
                this.RaisePropertyChanged("causa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataHijo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nombresField;
        
        private string apPaternoField;
        
        private string apMaternoField;
        
        private string fechaNaciField;
        
        private string fechaDefunField;
        
        private string estadoCivilField;
        
        private string sexoField;
        
        private ICEMinvuRutDataHijoDiscapacidad discapacidadField;
        
        private ICEMinvuRutDataHijoDiscapacidadRN discapacidadRNField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apPaterno {
            get {
                return this.apPaternoField;
            }
            set {
                this.apPaternoField = value;
                this.RaisePropertyChanged("apPaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string apMaterno {
            get {
                return this.apMaternoField;
            }
            set {
                this.apMaternoField = value;
                this.RaisePropertyChanged("apMaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaNaci {
            get {
                return this.fechaNaciField;
            }
            set {
                this.fechaNaciField = value;
                this.RaisePropertyChanged("fechaNaci");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaDefun {
            get {
                return this.fechaDefunField;
            }
            set {
                this.fechaDefunField = value;
                this.RaisePropertyChanged("fechaDefun");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("estadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ICEMinvuRutDataHijoDiscapacidad discapacidad {
            get {
                return this.discapacidadField;
            }
            set {
                this.discapacidadField = value;
                this.RaisePropertyChanged("discapacidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public ICEMinvuRutDataHijoDiscapacidadRN discapacidadRN {
            get {
                return this.discapacidadRNField;
            }
            set {
                this.discapacidadRNField = value;
                this.RaisePropertyChanged("discapacidadRN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataHijoDiscapacidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaVencField;
        
        private string mentalField;
        
        private string sensorialField;
        
        private string fisicaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaVenc {
            get {
                return this.fechaVencField;
            }
            set {
                this.fechaVencField = value;
                this.RaisePropertyChanged("fechaVenc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mental {
            get {
                return this.mentalField;
            }
            set {
                this.mentalField = value;
                this.RaisePropertyChanged("mental");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sensorial {
            get {
                return this.sensorialField;
            }
            set {
                this.sensorialField = value;
                this.RaisePropertyChanged("sensorial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fisica {
            get {
                return this.fisicaField;
            }
            set {
                this.fisicaField = value;
                this.RaisePropertyChanged("fisica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataHijoDiscapacidadRN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string indPermanenteField;
        
        private string fechaProximoDictamenField;
        
        private string gradoDiscapacidadGlobalField;
        
        private string causaPrincipalField;
        
        private ICEMinvuRutDataHijoDiscapacidadRNListaCausaSecundaria[] listaCausaSecundariaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string indPermanente {
            get {
                return this.indPermanenteField;
            }
            set {
                this.indPermanenteField = value;
                this.RaisePropertyChanged("indPermanente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string fechaProximoDictamen {
            get {
                return this.fechaProximoDictamenField;
            }
            set {
                this.fechaProximoDictamenField = value;
                this.RaisePropertyChanged("fechaProximoDictamen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string gradoDiscapacidadGlobal {
            get {
                return this.gradoDiscapacidadGlobalField;
            }
            set {
                this.gradoDiscapacidadGlobalField = value;
                this.RaisePropertyChanged("gradoDiscapacidadGlobal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string causaPrincipal {
            get {
                return this.causaPrincipalField;
            }
            set {
                this.causaPrincipalField = value;
                this.RaisePropertyChanged("causaPrincipal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaCausaSecundaria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public ICEMinvuRutDataHijoDiscapacidadRNListaCausaSecundaria[] listaCausaSecundaria {
            get {
                return this.listaCausaSecundariaField;
            }
            set {
                this.listaCausaSecundariaField = value;
                this.RaisePropertyChanged("listaCausaSecundaria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://info_persona.Schema_info_persona_Rice")]
    public partial class ICEMinvuRutDataHijoDiscapacidadRNListaCausaSecundaria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string causaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string causa {
            get {
                return this.causaField;
            }
            set {
                this.causaField = value;
                this.RaisePropertyChanged("causa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ope_prt_regcivil_info_persona", WrapperNamespace="http://minvu/ice/regcivil", IsWrapped=true)]
    public partial class ope_prt_regcivil_info_personaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://info_persona.Schema_info_persona_conice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://info_persona.Schema_info_persona_conice")]
        public Minvu.SectoresMedios.IData.ICE_RegistroCivil.Infopersona Infopersona;
        
        public ope_prt_regcivil_info_personaRequest() {
        }
        
        public ope_prt_regcivil_info_personaRequest(Minvu.SectoresMedios.IData.ICE_RegistroCivil.Infopersona Infopersona) {
            this.Infopersona = Infopersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ope_prt_regcivil_info_personaResponse", WrapperNamespace="http://minvu/ice/regcivil", IsWrapped=true)]
    public partial class ope_prt_regcivil_info_personaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://info_persona.Schema_info_persona_Rice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://info_persona.Schema_info_persona_Rice")]
        public Minvu.SectoresMedios.IData.ICE_RegistroCivil.ICE ICE;
        
        public ope_prt_regcivil_info_personaResponse() {
        }
        
        public ope_prt_regcivil_info_personaResponse(Minvu.SectoresMedios.IData.ICE_RegistroCivil.ICE ICE) {
            this.ICE = ICE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoapChannel : Minvu.SectoresMedios.IData.ICE_RegistroCivil.REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_RegistroCivil.REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap>, Minvu.SectoresMedios.IData.ICE_RegistroCivil.REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap {
        
        public REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoapClient() {
        }
        
        public REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaResponse Minvu.SectoresMedios.IData.ICE_RegistroCivil.REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap.ope_prt_regcivil_info_persona(Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaRequest request) {
            return base.Channel.ope_prt_regcivil_info_persona(request);
        }
        
        public Minvu.SectoresMedios.IData.ICE_RegistroCivil.ICE ope_prt_regcivil_info_persona(Minvu.SectoresMedios.IData.ICE_RegistroCivil.Infopersona Infopersona) {
            Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaRequest inValue = new Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaRequest();
            inValue.Infopersona = Infopersona;
            Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaResponse retVal = ((Minvu.SectoresMedios.IData.ICE_RegistroCivil.REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap)(this)).ope_prt_regcivil_info_persona(inValue);
            return retVal.ICE;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaResponse> Minvu.SectoresMedios.IData.ICE_RegistroCivil.REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap.ope_prt_regcivil_info_personaAsync(Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaRequest request) {
            return base.Channel.ope_prt_regcivil_info_personaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaResponse> ope_prt_regcivil_info_personaAsync(Minvu.SectoresMedios.IData.ICE_RegistroCivil.Infopersona Infopersona) {
            Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaRequest inValue = new Minvu.SectoresMedios.IData.ICE_RegistroCivil.ope_prt_regcivil_info_personaRequest();
            inValue.Infopersona = Infopersona;
            return ((Minvu.SectoresMedios.IData.ICE_RegistroCivil.REGCIVIL_orc_datos_persona_prt_regcivil_info_personaSoap)(this)).ope_prt_regcivil_info_personaAsync(inValue);
        }
    }
}
