//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PSSIM_DatosFuncionario.funcionarioSoap")]
    public interface funcionarioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosFuncionario", ReplyAction="*")]
        Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioResponse ObtenerDatosFuncionario(Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioResponse> ObtenerDatosFuncionarioAsync(Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosFuncionarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosFuncionario", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequestBody Body;
        
        public ObtenerDatosFuncionarioRequest() {
        }
        
        public ObtenerDatosFuncionarioRequest(Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosFuncionarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        public ObtenerDatosFuncionarioRequestBody() {
        }
        
        public ObtenerDatosFuncionarioRequestBody(string Username) {
            this.Username = Username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosFuncionarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosFuncionarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioResponseBody Body;
        
        public ObtenerDatosFuncionarioResponse() {
        }
        
        public ObtenerDatosFuncionarioResponse(Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosFuncionarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerDatosFuncionarioResult;
        
        public ObtenerDatosFuncionarioResponseBody() {
        }
        
        public ObtenerDatosFuncionarioResponseBody(string ObtenerDatosFuncionarioResult) {
            this.ObtenerDatosFuncionarioResult = ObtenerDatosFuncionarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface funcionarioSoapChannel : Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.funcionarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class funcionarioSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.funcionarioSoap>, Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.funcionarioSoap {
        
        public funcionarioSoapClient() {
        }
        
        public funcionarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public funcionarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public funcionarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public funcionarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioResponse Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.funcionarioSoap.ObtenerDatosFuncionario(Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequest request) {
            return base.Channel.ObtenerDatosFuncionario(request);
        }
        
        public string ObtenerDatosFuncionario(string Username) {
            Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequest inValue = new Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequest();
            inValue.Body = new Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequestBody();
            inValue.Body.Username = Username;
            Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioResponse retVal = ((Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.funcionarioSoap)(this)).ObtenerDatosFuncionario(inValue);
            return retVal.Body.ObtenerDatosFuncionarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioResponse> Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.funcionarioSoap.ObtenerDatosFuncionarioAsync(Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequest request) {
            return base.Channel.ObtenerDatosFuncionarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioResponse> ObtenerDatosFuncionarioAsync(string Username) {
            Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequest inValue = new Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequest();
            inValue.Body = new Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.ObtenerDatosFuncionarioRequestBody();
            inValue.Body.Username = Username;
            return ((Minvu.SectoresMedios.IData.PSSIM_DatosFuncionario.funcionarioSoap)(this)).ObtenerDatosFuncionarioAsync(inValue);
        }
    }
}
