//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_WorkFlowGestor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entrada", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Entrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_aplicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_tipo_eventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_tipo_objetoField;
        
        private int id_tipo_objetoField;
        
        private long id_objetoField;
        
        private int id_tipo_eventoField;
        
        private long id_objeto_hijoField;
        
        private long id_objeto_padreField;
        
        private long id_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string comentario_eventoField;
        
        private System.DateTime fecha_eventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lista_adjuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_grupoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo_aplicacion {
            get {
                return this.codigo_aplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_aplicacionField, value) != true)) {
                    this.codigo_aplicacionField = value;
                    this.RaisePropertyChanged("codigo_aplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo_tipo_evento {
            get {
                return this.codigo_tipo_eventoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_tipo_eventoField, value) != true)) {
                    this.codigo_tipo_eventoField = value;
                    this.RaisePropertyChanged("codigo_tipo_evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo_tipo_objeto {
            get {
                return this.codigo_tipo_objetoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_tipo_objetoField, value) != true)) {
                    this.codigo_tipo_objetoField = value;
                    this.RaisePropertyChanged("codigo_tipo_objeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_tipo_objeto {
            get {
                return this.id_tipo_objetoField;
            }
            set {
                if ((this.id_tipo_objetoField.Equals(value) != true)) {
                    this.id_tipo_objetoField = value;
                    this.RaisePropertyChanged("id_tipo_objeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long id_objeto {
            get {
                return this.id_objetoField;
            }
            set {
                if ((this.id_objetoField.Equals(value) != true)) {
                    this.id_objetoField = value;
                    this.RaisePropertyChanged("id_objeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int id_tipo_evento {
            get {
                return this.id_tipo_eventoField;
            }
            set {
                if ((this.id_tipo_eventoField.Equals(value) != true)) {
                    this.id_tipo_eventoField = value;
                    this.RaisePropertyChanged("id_tipo_evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long id_objeto_hijo {
            get {
                return this.id_objeto_hijoField;
            }
            set {
                if ((this.id_objeto_hijoField.Equals(value) != true)) {
                    this.id_objeto_hijoField = value;
                    this.RaisePropertyChanged("id_objeto_hijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long id_objeto_padre {
            get {
                return this.id_objeto_padreField;
            }
            set {
                if ((this.id_objeto_padreField.Equals(value) != true)) {
                    this.id_objeto_padreField = value;
                    this.RaisePropertyChanged("id_objeto_padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public long id_operacion {
            get {
                return this.id_operacionField;
            }
            set {
                if ((this.id_operacionField.Equals(value) != true)) {
                    this.id_operacionField = value;
                    this.RaisePropertyChanged("id_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string comentario_evento {
            get {
                return this.comentario_eventoField;
            }
            set {
                if ((object.ReferenceEquals(this.comentario_eventoField, value) != true)) {
                    this.comentario_eventoField = value;
                    this.RaisePropertyChanged("comentario_evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime fecha_evento {
            get {
                return this.fecha_eventoField;
            }
            set {
                if ((this.fecha_eventoField.Equals(value) != true)) {
                    this.fecha_eventoField = value;
                    this.RaisePropertyChanged("fecha_evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.id_usuarioField, value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string lista_adjuntos {
            get {
                return this.lista_adjuntosField;
            }
            set {
                if ((object.ReferenceEquals(this.lista_adjuntosField, value) != true)) {
                    this.lista_adjuntosField = value;
                    this.RaisePropertyChanged("lista_adjuntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string codigo_grupo {
            get {
                return this.codigo_grupoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_grupoField, value) != true)) {
                    this.codigo_grupoField = value;
                    this.RaisePropertyChanged("codigo_grupo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICE_WorkFlowGestor.WorkFlowGestorSoap")]
    public interface WorkFlowGestorSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento input del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarEvento", ReplyAction="*")]
        Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoResponse RegistrarEvento(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoResponse> RegistrarEventoAsync(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarEvento", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequestBody Body;
        
        public RegistrarEventoRequest() {
        }
        
        public RegistrarEventoRequest(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarEventoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.Entrada input;
        
        public RegistrarEventoRequestBody() {
        }
        
        public RegistrarEventoRequestBody(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.Entrada input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarEventoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoResponseBody Body;
        
        public RegistrarEventoResponse() {
        }
        
        public RegistrarEventoResponse(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarEventoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistrarEventoResult;
        
        public RegistrarEventoResponseBody() {
        }
        
        public RegistrarEventoResponseBody(string RegistrarEventoResult) {
            this.RegistrarEventoResult = RegistrarEventoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorkFlowGestorSoapChannel : Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.WorkFlowGestorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkFlowGestorSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.WorkFlowGestorSoap>, Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.WorkFlowGestorSoap {
        
        public WorkFlowGestorSoapClient() {
        }
        
        public WorkFlowGestorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkFlowGestorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowGestorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowGestorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoResponse Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.WorkFlowGestorSoap.RegistrarEvento(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequest request) {
            return base.Channel.RegistrarEvento(request);
        }
        
        public string RegistrarEvento(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.Entrada input) {
            Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequest inValue = new Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequest();
            inValue.Body = new Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequestBody();
            inValue.Body.input = input;
            Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoResponse retVal = ((Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.WorkFlowGestorSoap)(this)).RegistrarEvento(inValue);
            return retVal.Body.RegistrarEventoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoResponse> Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.WorkFlowGestorSoap.RegistrarEventoAsync(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequest request) {
            return base.Channel.RegistrarEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoResponse> RegistrarEventoAsync(Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.Entrada input) {
            Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequest inValue = new Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequest();
            inValue.Body = new Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.RegistrarEventoRequestBody();
            inValue.Body.input = input;
            return ((Minvu.SectoresMedios.IData.ICE_WorkFlowGestor.WorkFlowGestorSoap)(this)).RegistrarEventoAsync(inValue);
        }
    }
}
