//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RutType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class RutType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DV {
            get {
                return this.DVField;
            }
            set {
                if ((object.ReferenceEquals(this.DVField, value) != true)) {
                    this.DVField = value;
                    this.RaisePropertyChanged("DV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalidaType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class SalidaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.EstadoType EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RespuestaType RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.EstadoType Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RespuestaType Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class EstadoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class RespuestaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EncontradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.CiudadanoType CiudadanoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Encontrado {
            get {
                return this.EncontradoField;
            }
            set {
                if ((this.EncontradoField.Equals(value) != true)) {
                    this.EncontradoField = value;
                    this.RaisePropertyChanged("Encontrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.CiudadanoType Ciudadano {
            get {
                return this.CiudadanoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadanoField, value) != true)) {
                    this.CiudadanoField = value;
                    this.RaisePropertyChanged("Ciudadano");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CiudadanoType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class CiudadanoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RutType RutField;
        
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.DireccionType DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.ContactoType ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidCiudadanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechanacimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RutType Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.DireccionType Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.ContactoType Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Guid GuidCiudadano {
            get {
                return this.GuidCiudadanoField;
            }
            set {
                if ((this.GuidCiudadanoField.Equals(value) != true)) {
                    this.GuidCiudadanoField = value;
                    this.RaisePropertyChanged("GuidCiudadano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((this.EstadoCivilField.Equals(value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.DateTime> Fechanacimiento {
            get {
                return this.FechanacimientoField;
            }
            set {
                if ((this.FechanacimientoField.Equals(value) != true)) {
                    this.FechanacimientoField = value;
                    this.RaisePropertyChanged("Fechanacimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DireccionType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class DireccionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoblacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RegionType RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.ProvinciaType ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.ComunaType ComunaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Poblacion {
            get {
                return this.PoblacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PoblacionField, value) != true)) {
                    this.PoblacionField = value;
                    this.RaisePropertyChanged("Poblacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RegionType Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.ProvinciaType Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.ComunaType Comuna {
            get {
                return this.ComunaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunaField, value) != true)) {
                    this.ComunaField = value;
                    this.RaisePropertyChanged("Comuna");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactoType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class ContactoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoParticularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoMovilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtroTelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoParticular {
            get {
                return this.TelefonoParticularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoParticularField, value) != true)) {
                    this.TelefonoParticularField = value;
                    this.RaisePropertyChanged("TelefonoParticular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string TelefonoMovil {
            get {
                return this.TelefonoMovilField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoMovilField, value) != true)) {
                    this.TelefonoMovilField = value;
                    this.RaisePropertyChanged("TelefonoMovil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string TelefonoTrabajo {
            get {
                return this.TelefonoTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoTrabajoField, value) != true)) {
                    this.TelefonoTrabajoField = value;
                    this.RaisePropertyChanged("TelefonoTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string OtroTelefono {
            get {
                return this.OtroTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.OtroTelefonoField, value) != true)) {
                    this.OtroTelefonoField = value;
                    this.RaisePropertyChanged("OtroTelefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class RegionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private System.Guid GuidCrmField;
        
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid GuidCrm {
            get {
                return this.GuidCrmField;
            }
            set {
                if ((this.GuidCrmField.Equals(value) != true)) {
                    this.GuidCrmField = value;
                    this.RaisePropertyChanged("GuidCrm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProvinciaType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class ProvinciaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private System.Guid GuidCrmField;
        
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid GuidCrm {
            get {
                return this.GuidCrmField;
            }
            set {
                if ((this.GuidCrmField.Equals(value) != true)) {
                    this.GuidCrmField = value;
                    this.RaisePropertyChanged("GuidCrm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComunaType", Namespace="http://Minvu.Crm.Wcf")]
    [System.SerializableAttribute()]
    public partial class ComunaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private System.Guid GuidCrmField;
        
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid GuidCrm {
            get {
                return this.GuidCrmField;
            }
            set {
                if ((this.GuidCrmField.Equals(value) != true)) {
                    this.GuidCrmField = value;
                    this.RaisePropertyChanged("GuidCrm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Minvu.Crm.Wcf", ConfigurationName="ICE_CRM_Obtener_Datos_Persona.IObtenerCiudadano")]
    public interface IObtenerCiudadano {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Minvu.Crm.Wcf/IObtenerCiudadano/ObtenerCiudadanoCrm", ReplyAction="http://Minvu.Crm.Wcf/IObtenerCiudadano/ObtenerCiudadanoCrmResponse")]
        Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.SalidaType ObtenerCiudadanoCrm(Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RutType rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Minvu.Crm.Wcf/IObtenerCiudadano/ObtenerCiudadanoCrm", ReplyAction="http://Minvu.Crm.Wcf/IObtenerCiudadano/ObtenerCiudadanoCrmResponse")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.SalidaType> ObtenerCiudadanoCrmAsync(Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RutType rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObtenerCiudadanoChannel : Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.IObtenerCiudadano, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerCiudadanoClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.IObtenerCiudadano>, Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.IObtenerCiudadano {
        
        public ObtenerCiudadanoClient() {
        }
        
        public ObtenerCiudadanoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObtenerCiudadanoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObtenerCiudadanoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObtenerCiudadanoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.SalidaType ObtenerCiudadanoCrm(Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RutType rut) {
            return base.Channel.ObtenerCiudadanoCrm(rut);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.SalidaType> ObtenerCiudadanoCrmAsync(Minvu.SectoresMedios.IData.ICE_CRM_Obtener_Datos_Persona.RutType rut) {
            return base.Channel.ObtenerCiudadanoCrmAsync(rut);
        }
    }
}
