//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.WSSII_Rol {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://minvu/ice/sii", ConfigurationName="WSSII_Rol.SII_orc_inf_rol_prt_Datos_RolSoap")]
    public interface SII_orc_inf_rol_prt_Datos_RolSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://datosrol.Schema_datosrol_rice) no coincide con el valor predeterminado (http://minvu/ice/sii).
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu/ice/sii/SII_orc_inf_rol_prt_Datos_Rol/prt_Inf_rol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ICE")]
        Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolResponse prt_Inf_rol(Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://minvu/ice/sii/SII_orc_inf_rol_prt_Datos_Rol/prt_Inf_rol", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolResponse> prt_Inf_rolAsync(Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SII.Schema_datosrol_conice")]
    public partial class DatosRol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comunaField;
        
        private string manzanaField;
        
        private string predioField;
        
        private string periodoField;
        
        private string ussistField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("Comuna");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Manzana {
            get {
                return this.manzanaField;
            }
            set {
                this.manzanaField = value;
                this.RaisePropertyChanged("Manzana");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Predio {
            get {
                return this.predioField;
            }
            set {
                this.predioField = value;
                this.RaisePropertyChanged("Predio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Ussist {
            get {
                return this.ussistField;
            }
            set {
                this.ussistField = value;
                this.RaisePropertyChanged("Ussist");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datosrol.Schema_datosrol_rice")]
    public partial class ICE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERESULTADO rESULTADOField;
        
        private ICERESPUESTA rESPUESTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICERESULTADO RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ICERESPUESTA RESPUESTA {
            get {
                return this.rESPUESTAField;
            }
            set {
                this.rESPUESTAField = value;
                this.RaisePropertyChanged("RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datosrol.Schema_datosrol_rice")]
    public partial class ICERESULTADO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSTADOField;
        
        private string cODIGOField;
        
        private string dESCRIPCIONField;
        
        private string iD_RESPUESTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ID_RESPUESTA {
            get {
                return this.iD_RESPUESTAField;
            }
            set {
                this.iD_RESPUESTAField = value;
                this.RaisePropertyChanged("ID_RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datosrol.Schema_datosrol_rice")]
    public partial class ICERESPUESTA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERESPUESTARESP_HDR rESP_HDRField;
        
        private ICERESPUESTARESP_BODY rESP_BODYField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICERESPUESTARESP_HDR RESP_HDR {
            get {
                return this.rESP_HDRField;
            }
            set {
                this.rESP_HDRField = value;
                this.RaisePropertyChanged("RESP_HDR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ICERESPUESTARESP_BODY RESP_BODY {
            get {
                return this.rESP_BODYField;
            }
            set {
                this.rESP_BODYField = value;
                this.RaisePropertyChanged("RESP_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datosrol.Schema_datosrol_rice")]
    public partial class ICERESPUESTARESP_HDR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSTADOField;
        
        private string gLOSAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string GLOSA {
            get {
                return this.gLOSAField;
            }
            set {
                this.gLOSAField = value;
                this.RaisePropertyChanged("GLOSA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://datosrol.Schema_datosrol_rice")]
    public partial class ICERESPUESTARESP_BODY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cOMUNA_ACTUALField;
        
        private string mANZANA_ACTUALField;
        
        private string pREDIO_ACTUALField;
        
        private string dIR_PREDIALField;
        
        private string sERIEField;
        
        private string uBICACIONField;
        
        private string dESTINO_PRINCIPALField;
        
        private string nUM_MZ_BIEN_COMUNField;
        
        private string nUM_PRED_BIEN_COMUNField;
        
        private string fEC_INSCRIP_CBRField;
        
        private string tOT_APAGARField;
        
        private string aVL_TOTALField;
        
        private string aVL_EXENTOField;
        
        private string aGNO_TER_EXCField;
        
        private string aGNO_PERIODOField;
        
        private string sEMESTREField;
        
        private string aGNO_RESOLField;
        
        private string nUM_RESOLField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string COMUNA_ACTUAL {
            get {
                return this.cOMUNA_ACTUALField;
            }
            set {
                this.cOMUNA_ACTUALField = value;
                this.RaisePropertyChanged("COMUNA_ACTUAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string MANZANA_ACTUAL {
            get {
                return this.mANZANA_ACTUALField;
            }
            set {
                this.mANZANA_ACTUALField = value;
                this.RaisePropertyChanged("MANZANA_ACTUAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string PREDIO_ACTUAL {
            get {
                return this.pREDIO_ACTUALField;
            }
            set {
                this.pREDIO_ACTUALField = value;
                this.RaisePropertyChanged("PREDIO_ACTUAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DIR_PREDIAL {
            get {
                return this.dIR_PREDIALField;
            }
            set {
                this.dIR_PREDIALField = value;
                this.RaisePropertyChanged("DIR_PREDIAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SERIE {
            get {
                return this.sERIEField;
            }
            set {
                this.sERIEField = value;
                this.RaisePropertyChanged("SERIE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string UBICACION {
            get {
                return this.uBICACIONField;
            }
            set {
                this.uBICACIONField = value;
                this.RaisePropertyChanged("UBICACION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DESTINO_PRINCIPAL {
            get {
                return this.dESTINO_PRINCIPALField;
            }
            set {
                this.dESTINO_PRINCIPALField = value;
                this.RaisePropertyChanged("DESTINO_PRINCIPAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string NUM_MZ_BIEN_COMUN {
            get {
                return this.nUM_MZ_BIEN_COMUNField;
            }
            set {
                this.nUM_MZ_BIEN_COMUNField = value;
                this.RaisePropertyChanged("NUM_MZ_BIEN_COMUN");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string NUM_PRED_BIEN_COMUN {
            get {
                return this.nUM_PRED_BIEN_COMUNField;
            }
            set {
                this.nUM_PRED_BIEN_COMUNField = value;
                this.RaisePropertyChanged("NUM_PRED_BIEN_COMUN");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FEC_INSCRIP_CBR {
            get {
                return this.fEC_INSCRIP_CBRField;
            }
            set {
                this.fEC_INSCRIP_CBRField = value;
                this.RaisePropertyChanged("FEC_INSCRIP_CBR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string TOT_APAGAR {
            get {
                return this.tOT_APAGARField;
            }
            set {
                this.tOT_APAGARField = value;
                this.RaisePropertyChanged("TOT_APAGAR");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string AVL_TOTAL {
            get {
                return this.aVL_TOTALField;
            }
            set {
                this.aVL_TOTALField = value;
                this.RaisePropertyChanged("AVL_TOTAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string AVL_EXENTO {
            get {
                return this.aVL_EXENTOField;
            }
            set {
                this.aVL_EXENTOField = value;
                this.RaisePropertyChanged("AVL_EXENTO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string AGNO_TER_EXC {
            get {
                return this.aGNO_TER_EXCField;
            }
            set {
                this.aGNO_TER_EXCField = value;
                this.RaisePropertyChanged("AGNO_TER_EXC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string AGNO_PERIODO {
            get {
                return this.aGNO_PERIODOField;
            }
            set {
                this.aGNO_PERIODOField = value;
                this.RaisePropertyChanged("AGNO_PERIODO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string SEMESTRE {
            get {
                return this.sEMESTREField;
            }
            set {
                this.sEMESTREField = value;
                this.RaisePropertyChanged("SEMESTRE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string AGNO_RESOL {
            get {
                return this.aGNO_RESOLField;
            }
            set {
                this.aGNO_RESOLField = value;
                this.RaisePropertyChanged("AGNO_RESOL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string NUM_RESOL {
            get {
                return this.nUM_RESOLField;
            }
            set {
                this.nUM_RESOLField = value;
                this.RaisePropertyChanged("NUM_RESOL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="prt_Inf_rol", WrapperNamespace="http://minvu/ice/sii", IsWrapped=true)]
    public partial class prt_Inf_rolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SII.Schema_datosrol_conice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://SII.Schema_datosrol_conice")]
        public Minvu.SectoresMedios.IData.WSSII_Rol.DatosRol DatosRol;
        
        public prt_Inf_rolRequest() {
        }
        
        public prt_Inf_rolRequest(Minvu.SectoresMedios.IData.WSSII_Rol.DatosRol DatosRol) {
            this.DatosRol = DatosRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="prt_Inf_rolResponse", WrapperNamespace="http://minvu/ice/sii", IsWrapped=true)]
    public partial class prt_Inf_rolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://datosrol.Schema_datosrol_rice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://datosrol.Schema_datosrol_rice")]
        public Minvu.SectoresMedios.IData.WSSII_Rol.ICE ICE;
        
        public prt_Inf_rolResponse() {
        }
        
        public prt_Inf_rolResponse(Minvu.SectoresMedios.IData.WSSII_Rol.ICE ICE) {
            this.ICE = ICE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SII_orc_inf_rol_prt_Datos_RolSoapChannel : Minvu.SectoresMedios.IData.WSSII_Rol.SII_orc_inf_rol_prt_Datos_RolSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SII_orc_inf_rol_prt_Datos_RolSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.WSSII_Rol.SII_orc_inf_rol_prt_Datos_RolSoap>, Minvu.SectoresMedios.IData.WSSII_Rol.SII_orc_inf_rol_prt_Datos_RolSoap {
        
        public SII_orc_inf_rol_prt_Datos_RolSoapClient() {
        }
        
        public SII_orc_inf_rol_prt_Datos_RolSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SII_orc_inf_rol_prt_Datos_RolSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SII_orc_inf_rol_prt_Datos_RolSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SII_orc_inf_rol_prt_Datos_RolSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolResponse Minvu.SectoresMedios.IData.WSSII_Rol.SII_orc_inf_rol_prt_Datos_RolSoap.prt_Inf_rol(Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolRequest request) {
            return base.Channel.prt_Inf_rol(request);
        }
        
        public Minvu.SectoresMedios.IData.WSSII_Rol.ICE prt_Inf_rol(Minvu.SectoresMedios.IData.WSSII_Rol.DatosRol DatosRol) {
            Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolRequest inValue = new Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolRequest();
            inValue.DatosRol = DatosRol;
            Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolResponse retVal = ((Minvu.SectoresMedios.IData.WSSII_Rol.SII_orc_inf_rol_prt_Datos_RolSoap)(this)).prt_Inf_rol(inValue);
            return retVal.ICE;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolResponse> Minvu.SectoresMedios.IData.WSSII_Rol.SII_orc_inf_rol_prt_Datos_RolSoap.prt_Inf_rolAsync(Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolRequest request) {
            return base.Channel.prt_Inf_rolAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolResponse> prt_Inf_rolAsync(Minvu.SectoresMedios.IData.WSSII_Rol.DatosRol DatosRol) {
            Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolRequest inValue = new Minvu.SectoresMedios.IData.WSSII_Rol.prt_Inf_rolRequest();
            inValue.DatosRol = DatosRol;
            return ((Minvu.SectoresMedios.IData.WSSII_Rol.SII_orc_inf_rol_prt_Datos_RolSoap)(this)).prt_Inf_rolAsync(inValue);
        }
    }
}
