//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaType", Namespace="http://Minvu.RegistroCivil.Wcf")]
    [System.SerializableAttribute()]
    public partial class EntradaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.RutType RutField;
        
        private Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.CodTipoDocumentoType TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroSerieField;
        
        private int UssistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.RutType Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.CodTipoDocumentoType TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NumeroSerie {
            get {
                return this.NumeroSerieField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroSerieField, value) != true)) {
                    this.NumeroSerieField = value;
                    this.RaisePropertyChanged("NumeroSerie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Ussist {
            get {
                return this.UssistField;
            }
            set {
                if ((this.UssistField.Equals(value) != true)) {
                    this.UssistField = value;
                    this.RaisePropertyChanged("Ussist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RutType", Namespace="http://Minvu.RegistroCivil.Wcf")]
    [System.SerializableAttribute()]
    public partial class RutType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DV {
            get {
                return this.DVField;
            }
            set {
                if ((object.ReferenceEquals(this.DVField, value) != true)) {
                    this.DVField = value;
                    this.RaisePropertyChanged("DV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodTipoDocumentoType", Namespace="http://schemas.datacontract.org/2004/07/Minvu.RegistroCivil.Negocio.Cow.RegistroC" +
        "ivil")]
    public enum CodTipoDocumentoType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        S = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        T = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        D = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalidaType", Namespace="http://Minvu.RegistroCivil.Wcf")]
    [System.SerializableAttribute()]
    public partial class SalidaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.EstadoType EstadoConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.RespuestaType RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.EstadoType EstadoConsulta {
            get {
                return this.EstadoConsultaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoConsultaField, value) != true)) {
                    this.EstadoConsultaField = value;
                    this.RaisePropertyChanged("EstadoConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.RespuestaType Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoType", Namespace="http://Minvu.RegistroCivil.Wcf")]
    [System.SerializableAttribute()]
    public partial class EstadoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaType", Namespace="http://Minvu.RegistroCivil.Wcf")]
    [System.SerializableAttribute()]
    public partial class RespuestaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.RutType RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.DocumentoType TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.EstadoType ClaseDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroSerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndicadorVigenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndicadorBloqueoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.RutType Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.DocumentoType TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.EstadoType ClaseDocumento {
            get {
                return this.ClaseDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaseDocumentoField, value) != true)) {
                    this.ClaseDocumentoField = value;
                    this.RaisePropertyChanged("ClaseDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string NumeroSerie {
            get {
                return this.NumeroSerieField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroSerieField, value) != true)) {
                    this.NumeroSerieField = value;
                    this.RaisePropertyChanged("NumeroSerie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string IndicadorVigencia {
            get {
                return this.IndicadorVigenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicadorVigenciaField, value) != true)) {
                    this.IndicadorVigenciaField = value;
                    this.RaisePropertyChanged("IndicadorVigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVencimientoField, value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string IndicadorBloqueo {
            get {
                return this.IndicadorBloqueoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicadorBloqueoField, value) != true)) {
                    this.IndicadorBloqueoField = value;
                    this.RaisePropertyChanged("IndicadorBloqueo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoType", Namespace="http://Minvu.RegistroCivil.Wcf")]
    [System.SerializableAttribute()]
    public partial class DocumentoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICE_Consulta_Serie_Cedula_Identidad.IValidarDocumento")]
    public interface IValidarDocumento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidarDocumento/EstadoDocumento", ReplyAction="http://tempuri.org/IValidarDocumento/EstadoDocumentoResponse")]
        Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.SalidaType EstadoDocumento(Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.EntradaType entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidarDocumento/EstadoDocumento", ReplyAction="http://tempuri.org/IValidarDocumento/EstadoDocumentoResponse")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.SalidaType> EstadoDocumentoAsync(Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.EntradaType entrada);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidarDocumentoChannel : Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.IValidarDocumento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidarDocumentoClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.IValidarDocumento>, Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.IValidarDocumento {
        
        public ValidarDocumentoClient() {
        }
        
        public ValidarDocumentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidarDocumentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidarDocumentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidarDocumentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.SalidaType EstadoDocumento(Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.EntradaType entrada) {
            return base.Channel.EstadoDocumento(entrada);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.SalidaType> EstadoDocumentoAsync(Minvu.SectoresMedios.IData.ICE_Consulta_Serie_Cedula_Identidad.EntradaType entrada) {
            return base.Channel.EstadoDocumentoAsync(entrada);
        }
    }
}
