//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_evento
    {
        public int id_estado { get; set; }
        public int id_tipo_evento { get; set; }
    }
}
