//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public long id_evento { get; set; }
        public int id_estado { get; set; }
        public int id_tipo_evento { get; set; }
        public System.DateTime fecha_evento { get; set; }
        public string id_usuario { get; set; }
        public string codigo_grupo { get; set; }
        public string nivel_usuario { get; set; }
        public long id_operacion { get; set; }
        public string comentario_evento { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual instancia_objeto_workflow instancia_objeto_workflow { get; set; }
    }
}
