//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class instancia_objeto_workflow
    {
        public instancia_objeto_workflow()
        {
            this.evento = new HashSet<evento>();
            this.instancia_objeto_workflow1 = new HashSet<instancia_objeto_workflow>();
        }
    
        public int id_instancia_objeto { get; set; }
        public int id_tipo_objeto { get; set; }
        public int id_estado { get; set; }
        public long id_objeto { get; set; }
    
        public virtual ICollection<evento> evento { get; set; }
        public virtual ICollection<instancia_objeto_workflow> instancia_objeto_workflow1 { get; set; }
        public virtual instancia_objeto_workflow instancia_objeto_workflow2 { get; set; }
    }
}
