//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ERROR_SITIO
    {
        public int LOG_ID { get; set; }
        public string XML_ERR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
