//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class rukan_migraEntities : DbContext
    {
        public rukan_migraEntities()
            : base("name=rukan_migraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOG_ERROR_SITIO> LOG_ERROR_SITIO { get; set; }
    
        public virtual ObjectResult<string> Mensaje_SeleccionarPorCodigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Mensaje_SeleccionarPorCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<pa_Comuna_i_s_Result> pa_Comuna_i_s(Nullable<int> id_comuna)
        {
            var id_comunaParameter = id_comuna.HasValue ?
                new ObjectParameter("id_comuna", id_comuna) :
                new ObjectParameter("id_comuna", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Comuna_i_s_Result>("pa_Comuna_i_s", id_comunaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RUKAN_MIGRA_PROVINCIA_SELECCIONARPORCOMUNA(Nullable<int> comuna)
        {
            var comunaParameter = comuna.HasValue ?
                new ObjectParameter("comuna", comuna) :
                new ObjectParameter("comuna", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RUKAN_MIGRA_PROVINCIA_SELECCIONARPORCOMUNA", comunaParameter);
        }
    
        public virtual ObjectResult<RUKAN_MIGRA_usp_con_Comuna_Result> RUKAN_MIGRA_usp_con_Comuna(Nullable<int> id_region, Nullable<int> id_provincia)
        {
            var id_regionParameter = id_region.HasValue ?
                new ObjectParameter("id_region", id_region) :
                new ObjectParameter("id_region", typeof(int));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUKAN_MIGRA_usp_con_Comuna_Result>("RUKAN_MIGRA_usp_con_Comuna", id_regionParameter, id_provinciaParameter);
        }
    
        public virtual ObjectResult<RUKAN_MIGRA_USP_CON_COMUNA_PROVINCIA_REGION_Result> RUKAN_MIGRA_USP_CON_COMUNA_PROVINCIA_REGION(Nullable<int> cOMUNA)
        {
            var cOMUNAParameter = cOMUNA.HasValue ?
                new ObjectParameter("COMUNA", cOMUNA) :
                new ObjectParameter("COMUNA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUKAN_MIGRA_USP_CON_COMUNA_PROVINCIA_REGION_Result>("RUKAN_MIGRA_USP_CON_COMUNA_PROVINCIA_REGION", cOMUNAParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RUKAN_MIGRA_usp_con_COMUNASII_X_IDCOMUNA(Nullable<int> cOM_ID)
        {
            var cOM_IDParameter = cOM_ID.HasValue ?
                new ObjectParameter("COM_ID", cOM_ID) :
                new ObjectParameter("COM_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RUKAN_MIGRA_usp_con_COMUNASII_X_IDCOMUNA", cOM_IDParameter);
        }
    
        public virtual ObjectResult<RUKAN_MIGRA_usp_con_DOMINIO_Result> RUKAN_MIGRA_usp_con_DOMINIO(string dOM_ID_DOM)
        {
            var dOM_ID_DOMParameter = dOM_ID_DOM != null ?
                new ObjectParameter("DOM_ID_DOM", dOM_ID_DOM) :
                new ObjectParameter("DOM_ID_DOM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUKAN_MIGRA_usp_con_DOMINIO_Result>("RUKAN_MIGRA_usp_con_DOMINIO", dOM_ID_DOMParameter);
        }
    
        public virtual ObjectResult<RUKAN_MIGRA_USP_CON_REGION_SELECCION_TODOS_DS01_Result> RUKAN_MIGRA_USP_CON_REGION_SELECCION_TODOS_DS01()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUKAN_MIGRA_USP_CON_REGION_SELECCION_TODOS_DS01_Result>("RUKAN_MIGRA_USP_CON_REGION_SELECCION_TODOS_DS01");
        }
    
        public virtual ObjectResult<RUKAN_MIGRA_USP_PRC_SELECCIONAR_CONDICION_Result> RUKAN_MIGRA_USP_PRC_SELECCIONAR_CONDICION(Nullable<int> lIN_PRO, Nullable<int> lLA_ID, Nullable<int> oFE_ID, Nullable<int> dCB_APL_TIP, Nullable<int> dCB_CBR_TIP)
        {
            var lIN_PROParameter = lIN_PRO.HasValue ?
                new ObjectParameter("LIN_PRO", lIN_PRO) :
                new ObjectParameter("LIN_PRO", typeof(int));
    
            var lLA_IDParameter = lLA_ID.HasValue ?
                new ObjectParameter("LLA_ID", lLA_ID) :
                new ObjectParameter("LLA_ID", typeof(int));
    
            var oFE_IDParameter = oFE_ID.HasValue ?
                new ObjectParameter("OFE_ID", oFE_ID) :
                new ObjectParameter("OFE_ID", typeof(int));
    
            var dCB_APL_TIPParameter = dCB_APL_TIP.HasValue ?
                new ObjectParameter("DCB_APL_TIP", dCB_APL_TIP) :
                new ObjectParameter("DCB_APL_TIP", typeof(int));
    
            var dCB_CBR_TIPParameter = dCB_CBR_TIP.HasValue ?
                new ObjectParameter("DCB_CBR_TIP", dCB_CBR_TIP) :
                new ObjectParameter("DCB_CBR_TIP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUKAN_MIGRA_USP_PRC_SELECCIONAR_CONDICION_Result>("RUKAN_MIGRA_USP_PRC_SELECCIONAR_CONDICION", lIN_PROParameter, lLA_IDParameter, oFE_IDParameter, dCB_APL_TIPParameter, dCB_CBR_TIPParameter);
        }
    
        public virtual ObjectResult<RUKAN_MIGRA_USP_PRC_SELECCIONAR_PARAMETROS_Result> RUKAN_MIGRA_USP_PRC_SELECCIONAR_PARAMETROS(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUKAN_MIGRA_USP_PRC_SELECCIONAR_PARAMETROS_Result>("RUKAN_MIGRA_USP_PRC_SELECCIONAR_PARAMETROS", iDParameter);
        }
    
        public virtual int pa_Cambiar_Estado_Inscripcion_i_u(Nullable<int> idobjeto, string codigoestado, string descripcionestado)
        {
            var idobjetoParameter = idobjeto.HasValue ?
                new ObjectParameter("idobjeto", idobjeto) :
                new ObjectParameter("idobjeto", typeof(int));
    
            var codigoestadoParameter = codigoestado != null ?
                new ObjectParameter("codigoestado", codigoestado) :
                new ObjectParameter("codigoestado", typeof(string));
    
            var descripcionestadoParameter = descripcionestado != null ?
                new ObjectParameter("descripcionestado", descripcionestado) :
                new ObjectParameter("descripcionestado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cambiar_Estado_Inscripcion_i_u", idobjetoParameter, codigoestadoParameter, descripcionestadoParameter);
        }
    
        public virtual int pa_Cambiar_Estado_Interesado_i_u(Nullable<int> idobjeto, string codigoestado, string descripcionestado)
        {
            var idobjetoParameter = idobjeto.HasValue ?
                new ObjectParameter("idobjeto", idobjeto) :
                new ObjectParameter("idobjeto", typeof(int));
    
            var codigoestadoParameter = codigoestado != null ?
                new ObjectParameter("codigoestado", codigoestado) :
                new ObjectParameter("codigoestado", typeof(string));
    
            var descripcionestadoParameter = descripcionestado != null ?
                new ObjectParameter("descripcionestado", descripcionestado) :
                new ObjectParameter("descripcionestado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cambiar_Estado_Interesado_i_u", idobjetoParameter, codigoestadoParameter, descripcionestadoParameter);
        }
    
        public virtual int pa_Cambiar_Estado_Postulacion_i_u(Nullable<int> idobjeto, string codigoestado, string descripcionestado)
        {
            var idobjetoParameter = idobjeto.HasValue ?
                new ObjectParameter("idobjeto", idobjeto) :
                new ObjectParameter("idobjeto", typeof(int));
    
            var codigoestadoParameter = codigoestado != null ?
                new ObjectParameter("codigoestado", codigoestado) :
                new ObjectParameter("codigoestado", typeof(string));
    
            var descripcionestadoParameter = descripcionestado != null ?
                new ObjectParameter("descripcionestado", descripcionestado) :
                new ObjectParameter("descripcionestado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cambiar_Estado_Postulacion_i_u", idobjetoParameter, codigoestadoParameter, descripcionestadoParameter);
        }
    
        public virtual int pa_Cambiar_Estado_Subsidio_i_u(Nullable<int> idobjeto, string codigoestado, string descripcionestado)
        {
            var idobjetoParameter = idobjeto.HasValue ?
                new ObjectParameter("idobjeto", idobjeto) :
                new ObjectParameter("idobjeto", typeof(int));
    
            var codigoestadoParameter = codigoestado != null ?
                new ObjectParameter("codigoestado", codigoestado) :
                new ObjectParameter("codigoestado", typeof(string));
    
            var descripcionestadoParameter = descripcionestado != null ?
                new ObjectParameter("descripcionestado", descripcionestado) :
                new ObjectParameter("descripcionestado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cambiar_Estado_Subsidio_i_u", idobjetoParameter, codigoestadoParameter, descripcionestadoParameter);
        }
    
        public virtual int pa_Cambiar_Estado_Vivienda_i_u(Nullable<int> idobjeto, string codigoestado, string descripcionestado)
        {
            var idobjetoParameter = idobjeto.HasValue ?
                new ObjectParameter("idobjeto", idobjeto) :
                new ObjectParameter("idobjeto", typeof(int));
    
            var codigoestadoParameter = codigoestado != null ?
                new ObjectParameter("codigoestado", codigoestado) :
                new ObjectParameter("codigoestado", typeof(string));
    
            var descripcionestadoParameter = descripcionestado != null ?
                new ObjectParameter("descripcionestado", descripcionestado) :
                new ObjectParameter("descripcionestado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cambiar_Estado_Vivienda_i_u", idobjetoParameter, codigoestadoParameter, descripcionestadoParameter);
        }
    }
}
