//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICE_Ahorro_CajaLosAndes.Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_" +
        "SaldoSoap")]
    public interface Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice) no coincide con el valor predeterminado (http://tempuri.org/).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_Saldo" +
            "/InfoAhorro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ICE")]
        Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroResponse InfoAhorro(Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_Saldo" +
            "/InfoAhorro", ReplyAction="*")]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroResponse> InfoAhorroAsync(Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_conice")]
    public partial class ICE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string dvField;
        
        private string cuentaField;
        
        private string periodoField;
        
        private string ussistField;
        
        private string mesField;
        
        private string agnoField;
        
        private string nLlamadoField;
        
        private string programa_HabitacionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("Dv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Ussist {
            get {
                return this.ussistField;
            }
            set {
                this.ussistField = value;
                this.RaisePropertyChanged("Ussist");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("Mes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Agno {
            get {
                return this.agnoField;
            }
            set {
                this.agnoField = value;
                this.RaisePropertyChanged("Agno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string NLlamado {
            get {
                return this.nLlamadoField;
            }
            set {
                this.nLlamadoField = value;
                this.RaisePropertyChanged("NLlamado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Programa_Habitacional {
            get {
                return this.programa_HabitacionalField;
            }
            set {
                this.programa_HabitacionalField = value;
                this.RaisePropertyChanged("Programa_Habitacional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice")]
    public partial class ICE1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERESULTADO rESULTADOField;
        
        private ICERESPUESTA rESPUESTAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICERESULTADO RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ICERESPUESTA RESPUESTA {
            get {
                return this.rESPUESTAField;
            }
            set {
                this.rESPUESTAField = value;
                this.RaisePropertyChanged("RESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice")]
    public partial class ICERESULTADO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODIGOField;
        
        private string iD_RESPUESTAField;
        
        private string dESCRIPCIONField;
        
        private string eSTADOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID_RESPUESTA {
            get {
                return this.iD_RESPUESTAField;
            }
            set {
                this.iD_RESPUESTAField = value;
                this.RaisePropertyChanged("ID_RESPUESTA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice")]
    public partial class ICERESPUESTA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ICERESPUESTACabecera cabeceraField;
        
        private ICERESPUESTAEntrada entradaField;
        
        private ICERESPUESTASalida salidaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ICERESPUESTACabecera Cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("Cabecera");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ICERESPUESTAEntrada Entrada {
            get {
                return this.entradaField;
            }
            set {
                this.entradaField = value;
                this.RaisePropertyChanged("Entrada");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ICERESPUESTASalida Salida {
            get {
                return this.salidaField;
            }
            set {
                this.salidaField = value;
                this.RaisePropertyChanged("Salida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice")]
    public partial class ICERESPUESTACabecera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_msgField;
        
        private string id_servicioField;
        
        private string ipField;
        
        private string uRLField;
        
        private string fechaField;
        
        private string horaField;
        
        private string resultadoField;
        
        private string glosa_errorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Id_msg {
            get {
                return this.id_msgField;
            }
            set {
                this.id_msgField = value;
                this.RaisePropertyChanged("Id_msg");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Id_servicio {
            get {
                return this.id_servicioField;
            }
            set {
                this.id_servicioField = value;
                this.RaisePropertyChanged("Id_servicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("IP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("Hora");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Glosa_error {
            get {
                return this.glosa_errorField;
            }
            set {
                this.glosa_errorField = value;
                this.RaisePropertyChanged("Glosa_error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice")]
    public partial class ICERESPUESTAEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string num_ctaField;
        
        private string rutField;
        
        private string dv_RutField;
        
        private string mesField;
        
        private string usuarioField;
        
        private string sol_correlField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Num_cta {
            get {
                return this.num_ctaField;
            }
            set {
                this.num_ctaField = value;
                this.RaisePropertyChanged("Num_cta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Dv_Rut {
            get {
                return this.dv_RutField;
            }
            set {
                this.dv_RutField = value;
                this.RaisePropertyChanged("Dv_Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("Mes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Sol_correl {
            get {
                return this.sol_correlField;
            }
            set {
                this.sol_correlField = value;
                this.RaisePropertyChanged("Sol_correl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice")]
    public partial class ICERESPUESTASalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string status_ctaField;
        
        private string fecha_aperturaField;
        
        private string reajusteField;
        
        private string giros_posterioresField;
        
        private string plazo_orig_mesesField;
        
        private string monto_orig_UFField;
        
        private string plazo_modificadoField;
        
        private string monto_modificado_UFField;
        
        private string saldo_UF_mesField;
        
        private string saldo_UF_diaField;
        
        private string fecha_inicioField;
        
        private ICERESPUESTASalidaSaldo[] saldoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string status_cta {
            get {
                return this.status_ctaField;
            }
            set {
                this.status_ctaField = value;
                this.RaisePropertyChanged("status_cta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Fecha_apertura {
            get {
                return this.fecha_aperturaField;
            }
            set {
                this.fecha_aperturaField = value;
                this.RaisePropertyChanged("Fecha_apertura");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Reajuste {
            get {
                return this.reajusteField;
            }
            set {
                this.reajusteField = value;
                this.RaisePropertyChanged("Reajuste");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Giros_posteriores {
            get {
                return this.giros_posterioresField;
            }
            set {
                this.giros_posterioresField = value;
                this.RaisePropertyChanged("Giros_posteriores");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Plazo_orig_meses {
            get {
                return this.plazo_orig_mesesField;
            }
            set {
                this.plazo_orig_mesesField = value;
                this.RaisePropertyChanged("Plazo_orig_meses");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Monto_orig_UF {
            get {
                return this.monto_orig_UFField;
            }
            set {
                this.monto_orig_UFField = value;
                this.RaisePropertyChanged("Monto_orig_UF");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Plazo_modificado {
            get {
                return this.plazo_modificadoField;
            }
            set {
                this.plazo_modificadoField = value;
                this.RaisePropertyChanged("Plazo_modificado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Monto_modificado_UF {
            get {
                return this.monto_modificado_UFField;
            }
            set {
                this.monto_modificado_UFField = value;
                this.RaisePropertyChanged("Monto_modificado_UF");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Saldo_UF_mes {
            get {
                return this.saldo_UF_mesField;
            }
            set {
                this.saldo_UF_mesField = value;
                this.RaisePropertyChanged("Saldo_UF_mes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Saldo_UF_dia {
            get {
                return this.saldo_UF_diaField;
            }
            set {
                this.saldo_UF_diaField = value;
                this.RaisePropertyChanged("Saldo_UF_dia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                this.fecha_inicioField = value;
                this.RaisePropertyChanged("Fecha_inicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Saldo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public ICERESPUESTASalidaSaldo[] Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("Saldo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice")]
    public partial class ICERESPUESTASalidaSaldo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string saField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sa {
            get {
                return this.saField;
            }
            set {
                this.saField = value;
                this.RaisePropertyChanged("Sa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InfoAhorro", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InfoAhorroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_conice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_conice")]
        public Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.ICE ICE;
        
        public InfoAhorroRequest() {
        }
        
        public InfoAhorroRequest(Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.ICE ICE) {
            this.ICE = ICE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InfoAhorroResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InfoAhorroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://Minvu.CajaLosAndes.Schemas.sch_CajaLosAndesSaldo_rice")]
        public Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.ICE1 ICE;
        
        public InfoAhorroResponse() {
        }
        
        public InfoAhorroResponse(Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.ICE1 ICE) {
            this.ICE = ICE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoapChannel : Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoapClient : System.ServiceModel.ClientBase<Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoap>, Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoap {
        
        public Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoapClient() {
        }
        
        public Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroResponse Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoap.InfoAhorro(Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroRequest request) {
            return base.Channel.InfoAhorro(request);
        }
        
        public Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.ICE1 InfoAhorro(Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.ICE ICE) {
            Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroRequest inValue = new Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroRequest();
            inValue.ICE = ICE;
            Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroResponse retVal = ((Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoap)(this)).InfoAhorro(inValue);
            return retVal.ICE;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroResponse> Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoap.InfoAhorroAsync(Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroRequest request) {
            return base.Channel.InfoAhorroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroResponse> InfoAhorroAsync(Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.ICE ICE) {
            Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroRequest inValue = new Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.InfoAhorroRequest();
            inValue.ICE = ICE;
            return ((Minvu.SectoresMedios.IData.ICE_Ahorro_CajaLosAndes.Minvu_CajaLosAndes_orcCajaLosAndesSaldo_prt_CajaLosAndes_SaldoSoap)(this)).InfoAhorroAsync(inValue);
        }
    }
}
